
export const Types = {
  APP_SHOW_LOADING: 'APP_SHOW_LOADING',
  APP_HIDE_LOADING: 'APP_HIDE_LOADING',
  LOGIN_DO_FORGOT_PASS: 'LOGIN_DO_FORGOT_PASS',
  LOGIN_DO_LOGIN: 'LOGIN_DO_LOGIN',
  LOGOUT: 'LOGOUT',
  CREATE_CO_OWNER: 'CREATE_CO_OWNER',
}


