
export const Types = {
  APP_SHOW_LOADING: 'APP_SHOW_LOADING',
  APP_HIDE_LOADING: 'APP_HIDE_LOADING',
  LOGIN_DO_FORGOT_PASS: 'LOGIN_DO_FORGOT_PASS',
  LOGIN_DO_LOGIN: 'LOGIN_DO_LOGIN',
  LOGOUT: 'LOGOUT',
  CREATE_CO_OWNER: 'CREATE_CO_OWNER',
  CO_OWNER_GET_ALL: 'CO_OWNER_GET_ALL',
  CO_OWNER_REQUEST_ALL: 'CO_OWNER_REQUEST_ALL',
  PROFILE_GET_DATA: 'PROFILE_GET_DATA',
  PROFILE_REQUEST_DATA: 'PROFILE_REQUEST_DATA',
}


