
export const Types = {
  APP_SHOW_LOADING: 'APP_SHOW_LOADING',
  APP_HIDE_LOADING: 'APP_HIDE_LOADING',
  LOGIN_DO_FORGOT_PASS: 'LOGIN_DO_FORGOT_PASS',
  LOGIN_DO_LOGIN: 'LOGIN_DO_LOGIN',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_POST_LOGIN: 'LOGIN_POST_LOGIN',
  LOGOUT: 'LOGOUT',
  CO_OWNER_NEW_SUCCESS: 'CO_OWNER_NEW_SUCCESS',
  CO_OWNER_NEW_FAILED: 'CO_OWNER_NEW_FAILED',
  CO_OWNER_POST: 'CO_OWNER_POST',
  CO_OWNER_GET_ALL: 'CO_OWNER_GET_ALL',
  CO_OWNER_REQUEST_ALL: 'CO_OWNER_REQUEST_ALL',
  PROFILE_GET_DATA: 'PROFILE_GET_DATA',
  PROFILE_REQUEST_DATA: 'PROFILE_REQUEST_DATA',
}


